require("config.lazy")

vim.lsp.enable("lua_ls")
vim.lsp.enable("html")
vim.lsp.enable("clangd")
-- vim.lsp.enable('denols')
-- vim.lsp.enable("emmet_ls")
vim.lsp.enable("emmet_language_server")
-- vim.lsp.enable("denols")
vim.lsp.enable("ts_ls")
vim.lsp.enable("pylsp")
vim.lsp.enable("isort")
vim.lsp.enable("prettier")
vim.lsp.enable("marksman")
vim.lsp.enable("pylint")
vim.lsp.enable("stylua")
vim.lsp.enable("cssls")
vim.lsp.enable("angularls")
